- name: Install nginx repoository
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present

- name: Install yum packages from nginx
  yum: name={{ item }} state=installed enablerepo=nginx
  with_items:
    - nginx

- name: Run nginx
  service: name=nginx state=started enabled=yes
